force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <displayFormat>CN-{00000000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/DonationStaging__c.object-meta.xml
<CustomObject>
    <label>Donation Staging</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Donation Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donation Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DonationStaging__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Transaction amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Approval__c.field-meta.xml
<CustomField>
    <fullName>Approval__c</fullName>
    <label>Approval</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/BatchTimestamp__c.field-meta.xml
<CustomField>
    <fullName>BatchTimestamp__c</fullName>
    <description>Time of transaction execution</description>
    <externalId>true</externalId>
    <label>BatchTimestamp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/CurrencyId__c.field-meta.xml
<CustomField>
    <fullName>CurrencyId__c</fullName>
    <description>Transaction currency</description>
    <label>CurrencyId</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BYN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/OperationType__c.field-meta.xml
<CustomField>
    <fullName>OperationType__c</fullName>
    <label>OperationType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <description>Order number in WebPay</description>
    <label>OrderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <description>Method of transaction execution 
Possible values: cc - bank card, test - executed without real card processing</description>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>cc</fullName>
            </value>
            <value>
                <fullName>test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</description>
    <inlineHelpText>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/RC__c.field-meta.xml
<CustomField>
    <fullName>RC__c</fullName>
    <label>RC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/RCText__c.field-meta.xml
<CustomField>
    <fullName>RCText__c</fullName>
    <label>RCText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/RecurringToken__c.field-meta.xml
<CustomField>
    <fullName>RecurringToken__c</fullName>
    <label>RecurringToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/RRN__c.field-meta.xml
<CustomField>
    <fullName>RRN__c</fullName>
    <description>Transaction number in Visa/MasterCard</description>
    <inlineHelpText>Transaction number in Visa/MasterCard</inlineHelpText>
    <label>RRN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/SiteOrderId__c.field-meta.xml
<CustomField>
    <fullName>SiteOrderId__c</fullName>
    <description>Order number (name) assigned by the store</description>
    <label>SiteOrderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>Transaction number</description>
    <externalId>true</externalId>
    <label>TransactionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/recordTypes/Recurring.recordType-meta.xml
<RecordType>
    <fullName>Recurring</fullName>
    <active>true</active>
    <label>Recurring</label>
</RecordType>

force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recurring_Settings__mdt/Recurring_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Recurring Payment Settings</label>
    <pluralLabel>Recurring Payment Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Recurring_Settings__mdt/fields/Currency_Id__c.field-meta.xml
<CustomField>
    <fullName>Currency_Id__c</fullName>
    <label>Currency Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recurring_Settings__mdt/fields/Invoice_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Item_Name__c</fullName>
    <label>Invoice Item Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recurring_Settings__mdt/fields/Invoice_Item_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Item_Quantity__c</fullName>
    <label>Invoice Item Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recurring_Settings__mdt/fields/Notify_Url__c.field-meta.xml
<CustomField>
    <fullName>Notify_Url__c</fullName>
    <label>Notify Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recurring_Settings__mdt/fields/Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>Operation_Type__c</fullName>
    <label>Operation Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recurring_Settings__mdt/fields/Seed__c.field-meta.xml
<CustomField>
    <fullName>Seed__c</fullName>
    <label>Seed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recurring_Settings__mdt/fields/Test__c.field-meta.xml
<CustomField>
    <fullName>Test__c</fullName>
    <label>Test</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recurring_Settings__mdt/fields/Wsb_Version__c.field-meta.xml
<CustomField>
    <fullName>Wsb_Version__c</fullName>
    <label>Wsb Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/RecurringDonation__c.object-meta.xml
<CustomObject>
    <label>Recurring Donation</label>
    <nameField>
        <displayFormat>RD-{00000000}</displayFormat>
        <label>Recurring Donations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RecurringDonation__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <formula>Contact__r.CustomerId__c</formula>
    <label>CustomerId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <formula>Contact__r.OrderNumber__c</formula>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/RecurringToken__c.field-meta.xml
<CustomField>
    <fullName>RecurringToken__c</fullName>
    <label>Recurring Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WebPayDonationRequest.cls
public with sharing class WebPayDonationRequest {
    
    private static final String PAYMENT_TYPE_FAILED = '8';

    private static Recurring_Settings__mdt mtd;
    
    static{
        mtd = getCustomMetadata();
    }
    
    public static void sendPaymentRequest(List<RecurringDonation__c> recurrings){

        System.debug('WebPayDonationRequest.sendPaymentRequest();');
        System.debug('Recurrings - ' + recurrings);
        
        try {
            if (recurrings.size() > Limits.getLimitCallouts()){
                throw new LimitException();
            }
            Map<String,String> headers = new Map<String, String>();
            headers.put('Content-Type', 'application/x-www-form-urlencoded');
            headers.put('Accept', 'application/json');
            
            List<Integration_Log__c> logs = new List<Integration_Log__c>();
            
            //List<WebPayDonationResponseWrapper> responses = new List<WebPayDonationResponseWrapper>();

            for (RecurringDonation__c recurring : recurrings){
                String payload = getPayload(recurring);
                System.debug('Payload = ' + payload);
                HttpResponse res = RestClient.makeRequest(headers, mtd.Endpoint__c, 'POST', payload);
            
                System.debug('RESPONSE BODY '+res.getBody());

                WebPayDonationRequest.WebPayDonationResponseWrapper wrappedResponse = 
                    (WebPayDonationRequest.WebPayDonationResponseWrapper) 
                    JSON.deserialize(res.getBody(), WebPayDonationRequest.WebPayDonationResponseWrapper.class);

                // responses.add(wrappedResponse);

                logs.add(
                    Utility.configureIntegrationLog(
                        'WebPay', 
                        Utility.LogLevels.DEBUG,
                        Utility.STAGING_RECORD_TYPE_RECURRING,
                        'WebPayDonationRequest: Processed RecurringDonation Record', 
                        JSON.serialize(recurring)
                    )
                );

                logs.add(
                    Utility.configureIntegrationLog(
                        'WebPay', 
                        Utility.LogLevels.DEBUG,
                        Utility.STAGING_RECORD_TYPE_RECURRING,
                        'WebPayDonationRequest response: '+ wrappedResponse.rc_text, 
                        JSON.serialize(wrappedResponse)
                    )
                );
                System.debug('HttpResponse res = ' + res);
            }
            insert logs;

            //createDonationStagingRecords(responses);
        } catch (LimitException ex) {
            insert Utility.configureIntegrationLog(
                'WebPay', Utility.LogLevels.FATAL,
                Utility.STAGING_RECORD_TYPE_RECURRING,
                'WebPayDonationRequest: LimitCallouts Exception, ' + ex.getMessage(),
                ex.getStackTraceString()
            );
        } catch (Exception ex) {
            insert Utility.configureIntegrationLog(
                'WebPay', Utility.LogLevels.FATAL,
                Utility.STAGING_RECORD_TYPE_RECURRING,
                'WebPayDonationRequest: Exception, ' + ex.getMessage(),
                ex.getStackTraceString()
            );
        }
        
    }

    // private static void createDonationStagingRecords(List<WebPayDonationResponseWrapper> responses) {
    //     List<Integration_Log__c> logs = new List<Integration_Log__c>();
    //     List<DonationStaging__c> newStagings = new List<DonationStaging__c>();
        
    //     for (WebPayDonationResponseWrapper response : responses) {
    //         if (response.payment_type == PAYMENT_TYPE_FAILED) {
    //             DonationStaging__c newStagingFailed = parseResponseIntoDonationStaging(response);
    //             newStagingFailed.RecordTypeId = Utility.getRecordTypeId(Utility.STAGING_API_NAME, Utility.STAGING_RECORD_TYPE_RECURRING);
    //             newStagingFailed.Status__c = Utility.mainSettings.Default_New_Staging_Status__c;
    //             newStagings.add(newStagingFailed);

    //             logs.add(
    //                 Utility.configureIntegrationLog(
    //                     'WebPay', 
    //                     Utility.LogLevels.DEBUG,
    //                     Utility.STAGING_RECORD_TYPE_RECURRING, 
    //                     'WebPayDonationRequest: '+Datetime.now()+' Created Failed DonationStaging__c', 
    //                     JSON.serialize(newStagingFailed)
    //                 )
    //             );
    //         }
    //     }
        
    //     System.debug('DonationStaging__c newStagings = ' + newStagings);

    //     StagingService.proceedInsertings(newStagings);
        
    //     insert logs;
    // }

    private static DonationStaging__c parseResponseIntoDonationStaging(WebPayDonationResponseWrapper response) {
        return new DonationStaging__c(
            BatchTimestamp__c = response.batch_timestamp,
            CurrencyId__c     = response.currency_id,
            Amount__c         = response.amount,
            PaymentMethod__c  = response.payment_method,
            OrderId__c        = response.order_id,
            SiteOrderId__c    = response.site_order_id,
            TransactionId__c  = response.transaction_id,
            PaymentType__c    = response.payment_type,
            RRN__c            = response.rrn,
            Action__c         = response.action,
            RC__c             = response.rc,
            Approval__c       = response.approval,
            Card__c           = response.card,
            CustomerId__c     = response.customer_id,
            RecurringToken__c = response.recurring_token,
            RCText__c         = response.rc_text,
            OperationType__c  = response.operation_type       
        );
    }
    
    private static String getPayload(RecurringDonation__c recurring) {
        Map<String, String> vals = generatePayload(recurring);   
        String result = '';
        for(String thisKey : vals.keySet()) {
            result += thisKey + '=' + vals.get(thisKey) + '&';
        }
        return result.removeEnd('&');    
    }
    
    private static String sha1Generator(Map<String, String> req){
        String toConvert = req.get('wsb_seed');
        toConvert += req.get('wsb_storeid');
        toConvert += req.get('wsb_customer_id');
        toConvert += req.get('wsb_order_num');
        toConvert += req.get('wsb_test');
        toConvert += req.get('wsb_currency_id');
        toConvert += req.get('wsb_total');
        toConvert += req.get('wsb_operation_type');
        toConvert += req.get('wsb_recurring_token');
        toConvert += mtd.Secret_Key__c;
        String shasign = EncodingUtil.convertToHex(Crypto.generateDigest('SHA1',Blob.valueOf(toConvert)));
        return shasign;
    }
    
    private static Map<String, String> generatePayload(RecurringDonation__c recurring) {
        Map<String, String> req = new Map<String, String>();
        req.put('wsb_version', mtd.Wsb_Version__c);
        req.put('wsb_storeid', mtd.Store_Id__c);
        req.put('wsb_operation_type', mtd.Operation_Type__c);
        req.put('wsb_test', mtd.Test__c);
        req.put('wsb_currency_id', mtd.Currency_Id__c);
        req.put('wsb_seed', mtd.Seed__c);
        req.put('wsb_notify_url', mtd.Notify_Url__c);
        req.put('wsb_recurring_token', recurring.RecurringToken__c);
        req.put('wsb_invoice_item_name[0]', mtd.Invoice_Item_Name__c);
        req.put('wsb_invoice_item_quantity[0]', mtd.Invoice_Item_Quantity__c);
        req.put('wsb_invoice_item_price[0]', String.valueOf(recurring.Amount__c));
        Double total = Double.valueOf(mtd.Invoice_Item_Quantity__c) * Double.valueOf(recurring.Amount__c);
        req.put('wsb_total', String.valueOf(total));
        req.put('wsb_customer_id', recurring.CustomerId__c);
        req.put('wsb_order_num', recurring.OrderNumber__c);
        req.put('wsb_email', recurring.Email__c);
        req.put('wsb_signature', sha1Generator(req));
        return req;
    }
    
    private static Recurring_Settings__mdt getCustomMetadata() {
        return [
            SELECT Currency_Id__c, Endpoint__c, Invoice_Item_Name__c, Invoice_Item_Quantity__c, 
            Notify_Url__c, Operation_Type__c, Secret_Key__c, Seed__c, Store_Id__c, Test__c, Wsb_Version__c
            FROM Recurring_Settings__mdt LIMIT 1
        ];
    }
    
    public class LimitException extends Exception {
        public override String getMessage() {
            return 'Limit Exception. APEX Batch size should be < ' + Limits.getLimitCallouts();
        }
    }
    
    public with sharing class WebPayDonationResponseWrapper {
        public String batch_timestamp;
        public String currency_id;
        public Integer amount;
        public String customer_id;
        public String payment_method;
        public String site_order_id;
        public String operation_type;
        public String order_id;
        public String terminal;
        public String transaction_id;
        public String recurring_token;
        public String payment_type;
        public String rrn;
        public String rc;
        public String rc_text;
        public String action;
        public String approval;
        public String card;
    }
    

}