force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <displayFormat>CN-{00000000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Card__c/fields/ValidThru__c.field-meta.xml
<CustomField>
    <fullName>ValidThru__c</fullName>
    <label>Valid Thru</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ActivityBatch.cls
public without sharing class ActivityBatch implements Database.Batchable<sObject>, Database.Stateful {    
    
    public static Database.QueryLocator start(Database.BatchableContext bc) {
        String cardStatusOpen = 'Active';
        String query = 'SELECT Contact__c, Contact__r.OwnerId, Contact__r.Email, ValidThru__c FROM Card__c ';
        query += ' WHERE Status__c =: cardStatusOpen AND Contact__r.Email != null AND  ValidThru__c = YESTERDAY LIMIT 50000';
        return Database.getQueryLocator(query);
    }
    
    public static void execute(Database.BatchableContext bc, List<Card__c> cards){
        List<Contact> contacts = ActivityService.prepareContactsForCardReactivationEmailSending(cards);
        ActivityService.sendCardReactivationEmails(contacts);
    }
    
    public static void finish(Database.BatchableContext bc){
    }    
    
}