force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <displayFormat>CN-{00000000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/DonationStaging__c.object-meta.xml
<CustomObject>
    <label>Donation Staging</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Donation Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donation Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DonationStaging__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Transaction amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Approval__c.field-meta.xml
<CustomField>
    <fullName>Approval__c</fullName>
    <label>Approval</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/BatchTimestamp__c.field-meta.xml
<CustomField>
    <fullName>BatchTimestamp__c</fullName>
    <description>Time of transaction execution</description>
    <externalId>true</externalId>
    <label>BatchTimestamp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Cardholder__c.field-meta.xml
<CustomField>
    <fullName>Cardholder__c</fullName>
    <label>Cardholder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/CurrencyId__c.field-meta.xml
<CustomField>
    <fullName>CurrencyId__c</fullName>
    <description>Transaction currency</description>
    <label>CurrencyId</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BYN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/OfferExpDate__c.field-meta.xml
<CustomField>
    <fullName>OfferExpDate__c</fullName>
    <label>OfferExpDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/OperationType__c.field-meta.xml
<CustomField>
    <fullName>OperationType__c</fullName>
    <label>OperationType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <description>Order number in WebPay</description>
    <label>OrderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <description>Method of transaction execution 
Possible values: cc - bank card, test - executed without real card processing</description>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>cc</fullName>
            </value>
            <value>
                <fullName>test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</description>
    <inlineHelpText>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/RC__c.field-meta.xml
<CustomField>
    <fullName>RC__c</fullName>
    <label>RC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/RCText__c.field-meta.xml
<CustomField>
    <fullName>RCText__c</fullName>
    <label>RCText</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/RecurringToken__c.field-meta.xml
<CustomField>
    <fullName>RecurringToken__c</fullName>
    <label>RecurringToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/RRN__c.field-meta.xml
<CustomField>
    <fullName>RRN__c</fullName>
    <description>Transaction number in Visa/MasterCard</description>
    <inlineHelpText>Transaction number in Visa/MasterCard</inlineHelpText>
    <label>RRN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/SiteOrderId__c.field-meta.xml
<CustomField>
    <fullName>SiteOrderId__c</fullName>
    <description>Order number (name) assigned by the store</description>
    <label>SiteOrderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>Transaction number</description>
    <externalId>true</externalId>
    <label>TransactionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/WsbSignature__c.field-meta.xml
<CustomField>
    <fullName>WsbSignature__c</fullName>
    <description>Electronic signature.
The electronic signature is calculated if the Secret Key is specified in billing settings
http://www.sha1-online.com/</description>
    <label>WsbSignature</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Xml__c.field-meta.xml
<CustomField>
    <fullName>Xml__c</fullName>
    <label>Xml</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ParseService.cls
public with sharing class ParseService {
    
    // private static DonationStaging__c newStaging; 
    
    // static{
    //     newStaging = new DonationStaging__c(Status__c = Utility.mainSettings.Default_New_Staging_Status__c);
    // }
    

    public static DonationStaging__c parseXML(String strXml){
        DonationStaging__c newStaging = new DonationStaging__c(Status__c = Utility.mainSettings.Default_New_Staging_Status__c);
        newStaging.Xml__c = strXml;
        Dom.Document doc = new Dom.Document();
        doc.load(strXml);
        Dom.XMLNode root = doc.getRootElement();
        walkThrough(root, newStaging);
        return newStaging;
    }
    
    private static void walkThrough(DOM.XMLNode node, DonationStaging__c newStaging) {
        Map<String, String> xmlToStaging = xmlToStaging();
        if (node.getNodeType() == DOM.XMLNodeType.ELEMENT) {
            String nodeName = node.getName();
            String nodeText = node.getText();
            String stagingField = xmlToStaging.get(nodeName);
            if (String.isNotEmpty(stagingField)){
                buildStaging(stagingField, nodeText, newStaging);
            }

        }
        for (Dom.XMLNode child: node.getChildElements()) {
            walkThrough(child, newStaging);
        }
    }
    
    private static void buildStaging(String field, String value, DonationStaging__c newStaging) {
        Schema.DisplayType typeFieldValue = Utility.getFieldType(Utility.STAGING_API_NAME, field);
        if (typeFieldValue == Schema.DisplayType.Double){
            newStaging.put(field, Decimal.valueOf(value));
        }else{
            newStaging.put(field, value);
        }
    }
    
    private static Map<String, String> xmlToStaging() {
        return new Map<String, String> {
            'BatchTimestamp' => 'BatchTimestamp__c',
            'CurrencyId' => 'CurrencyId__c',
            'Amount' => 'Amount__c',
            'PaymentMethod' => 'PaymentMethod__c',
            'OrderId' => 'OrderId__c',
            'SiteOrderId' => 'SiteOrderId__c',
            'TransactionId' => 'TransactionId__c',
            'PaymentType' => 'PaymentType__c',
            'RRN' => 'RRN__c',
            'WsbSignature' => 'WsbSignature__c',
            'Action' => 'Action__c',
            'RC' => 'RC__c',
            'Approval' => 'Approval__c',
            'Card' => 'Card__c',
            'Cardholder' => 'Cardholder__c',
            'CustomerId' => 'CustomerId__c',
            'RecurringToken' => 'RecurringToken__c',
            'OfferExpDate' => 'OfferExpDate__c',
            'RCText' => 'RCText__c',
            'OperationType' => 'OperationType__c'                
        };
    }
}