force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <displayFormat>CN-{00000000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Card__c/fields/ValidThru__c.field-meta.xml
<CustomField>
    <fullName>ValidThru__c</fullName>
    <label>Valid Thru</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>Contains information about country cities</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>The district to which the city belongs</description>
    <inlineHelpText>The district to which the city belongs</inlineHelpText>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/City_District__c/City_District__c.object-meta.xml
<CustomObject>
    <label>City District</label>
    <nameField>
        <label>City District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City Districts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/City_District__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>The city to which the city district belongs</description>
    <inlineHelpText>The city to which the city district belongs</inlineHelpText>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>City Districts</relationshipLabel>
    <relationshipName>City_Districts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>The region to which the district belongs</description>
    <inlineHelpText>The region to which the district belongs</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/DonationStaging__c.object-meta.xml
<CustomObject>
    <label>Donation Staging</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Donation Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donation Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DonationStaging__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Transaction amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/BatchTimestamp__c.field-meta.xml
<CustomField>
    <fullName>BatchTimestamp__c</fullName>
    <description>Time of transaction execution</description>
    <externalId>true</externalId>
    <label>BatchTimestamp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/OfferExpDate__c.field-meta.xml
<CustomField>
    <fullName>OfferExpDate__c</fullName>
    <label>OfferExpDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</description>
    <inlineHelpText>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/RecurringToken__c.field-meta.xml
<CustomField>
    <fullName>RecurringToken__c</fullName>
    <label>RecurringToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/SiteOrderId__c.field-meta.xml
<CustomField>
    <fullName>SiteOrderId__c</fullName>
    <description>Order number (name) assigned by the store</description>
    <label>SiteOrderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>Transaction number</description>
    <externalId>true</externalId>
    <label>TransactionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/recordTypes/Initiation.recordType-meta.xml
<RecordType>
    <fullName>Initiation</fullName>
    <active>true</active>
    <label>Initiation</label>
</RecordType>

force-app/main/default/objects/DonationStaging__c/recordTypes/Recurring.recordType-meta.xml
<RecordType>
    <fullName>Recurring</fullName>
    <active>true</active>
    <label>Recurring</label>
</RecordType>

force-app/main/default/objects/RC_Recurring_Donation_Settings__c/RC_Recurring_Donation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>These settings configured periods of time for the next payment attempts</description>
    <label>RC Recurring Donation Settings</label>
</CustomObject>

force-app/main/default/objects/RC_Recurring_Donation_Settings__c/fields/Fourth_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Fourth_Attempt__c</fullName>
    <description>This parameter indicates the number of days to make fourth payment attempt</description>
    <inlineHelpText>This parameter indicates the number of days to make fourth payment attempt</inlineHelpText>
    <label>Fourth Attempt</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_Recurring_Donation_Settings__c/fields/Second_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Second_Attempt__c</fullName>
    <description>This parameter indicates the number of days to make second payment attempt</description>
    <inlineHelpText>This parameter indicates the number of days to make second payment attempt</inlineHelpText>
    <label>Second Attempt</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_Recurring_Donation_Settings__c/fields/Third_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Third_Attempt__c</fullName>
    <description>This parameter indicates the number of days to make third payment attempt</description>
    <inlineHelpText>This parameter indicates the number of days to make third payment attempt</inlineHelpText>
    <label>Third Attempt</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/RecurringDonation__c.object-meta.xml
<CustomObject>
    <label>Recurring Donation</label>
    <nameField>
        <displayFormat>RD-{00000000}</displayFormat>
        <label>Recurring Donations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RecurringDonation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>RecurringDonations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <formula>Contact__r.CustomerId__c</formula>
    <label>CustomerId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/LastPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>LastPaymentDate__c</fullName>
    <description>Last success payment date</description>
    <inlineHelpText>Last success payment date</inlineHelpText>
    <label>Last Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/NextPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>NextPaymentDate__c</fullName>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/OfferExpDate__c.field-meta.xml
<CustomField>
    <fullName>OfferExpDate__c</fullName>
    <label>Offer Exp Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <formula>Contact__r.OrderNumber__c</formula>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/PaymentDay__c.field-meta.xml
<CustomField>
    <fullName>PaymentDay__c</fullName>
    <formula>Contact__r.PaymentDay__c</formula>
    <label>Payment Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/RecurringToken__c.field-meta.xml
<CustomField>
    <fullName>RecurringToken__c</fullName>
    <label>Recurring Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>Contains information about country regions</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {
    
    private static final String STAGING_BATCHTIMESTAMP = '1565877873';
    private static final Decimal STAGING_AMOUNT = 1;
    private static final String STAGING_PAYMENT_TYPE = '10';
    private static final String STAGING_EXP_DATE = '2020-11-30';
    private static final String RECURRING_TOKEN = '920762012';
    
    public static void createTestData() {
        
        RC_Recurring_Donation_Settings__c settings = new RC_Recurring_Donation_Settings__c(
            Name = 'Payment attempt settings',
            Second_Attempt__c = 1.0,
            Third_Attempt__c = 3.0,
            Fourth_Attempt__c = 14.0
        );
        insert settings;
        
        Account redCross = generateAccount('Red Cross', Utility.getRecordTypeId('Account', 'Organization'));
        Account globalAgency = generateAccount('GlobalAgency', Utility.getRecordTypeId('Account', 'Organization'));
        insert new List<Account>{redCross, globalAgency}; 
            
        Lead tabitha = TestDataFactory.generateLead('Tabitha', 'Myers', 'Red Cross', 'tabitha@mail.com', '10', '10', 1); // for Initiation Payment
        Lead jerry = TestDataFactory.generateLead('Jerry', 'Myers', 'Red Cross', 'jerry@mail.com', '20', '20', null); // for OneTime Payment
        insert new List<Lead>{tabitha, jerry};
            
        Contact alex = generateContact('Alex', 'Oakes', redCross.Id, '', '', null); //red cross employee
        Contact bob = TestDataFactory.generateContact('Bob', 'Furguston', redCross.Id, '40', '40', 1); // for Initiation Payment
        bob.Email = 'bob@gmail.com';
        Contact barbara = TestDataFactory.generateContact('Barbara', 'Furguston', redCross.Id, '50', '50', null); // for OneTime Payment
        Contact john = TestDataFactory.generateContact('John', 'Smith', redCross.Id, '60', '60', 1); // for Recurring Payment
        insert new List<Contact>{alex, bob, barbara, john};


        
    }
    
    public static Contact generateContact(String fname, String lname, Id accountId, String customerId, String orderNumber, Integer paymentDay) {
        Contact theContact = new Contact();
        theContact.FirstName = fname;
        theContact.LastName = lname;
        theContact.AccountId = accountId;
        theContact.CustomerId__c = customerId;
        theContact.OrderNumber__c = orderNumber;
        theContact.PaymentDay__c = paymentDay;
        return theContact;
    }
    
    public static RecurringDonation__c generateRecurringDonation(Decimal amount, Id contId, Date last, Date next){
        RecurringDonation__c recurring = new RecurringDonation__c();
        recurring.Amount__c = amount;
        recurring.Contact__c = contId;
        recurring.LastPaymentDate__c = last;
        recurring.NextPaymentDate__c = next;
        recurring.RecurringToken__c = RECURRING_TOKEN;
        recurring.Status__c = 'Active';
        return recurring;
    }
    
    public static Lead generateLead(String fName, String lName, String company, String email, String customerId, String orderNumber, Integer paymentDay) {
        Lead theLead = new Lead();
        theLead.Lastname = lName;
        theLead.Firstname = fName;
        theLead.company = company;
        theLead.Email = email;
        theLead.CustomerId__c = customerId;
        theLead.OrderNumber__c = orderNumber;
        theLead.PaymentDay__c = paymentDay;
        return theLead;
    }
    
    public static Account generateAccount(String name, String recordTypeId) {
        Account theAccount = new Account();
        theAccount.Name = name;
        theAccount.RecordTypeId = recordTypeId;
        return theAccount;
    }
    
    public static npe01__OppPayment__c generatePayment(Date paymentDate, Boolean paid, Id oppId, Id contactId){
        npe01__OppPayment__c payment = new npe01__OppPayment__c();
        payment.npe01__Payment_Date__c = paymentDate;
        payment.npe01__Paid__c = paid;
        payment.npe01__Opportunity__c = oppId;
        payment.Contact__c = contactId;
        return payment;
    }
    
    public static DonationStaging__c generateRecuringStaging(String customerOrderId, String siteOrderId, String transactionId, Decimal amount, String paymentType) {
        DonationStaging__c staging = new DonationStaging__c();
        staging.BatchTimestamp__c = STAGING_BATCHTIMESTAMP;
        staging.CustomerId__c = customerOrderId;
        staging.SiteOrderId__c = siteOrderId;
        staging.TransactionId__c = transactionId;
        staging.Amount__c = amount;
        staging.PaymentType__c = paymentType;
        return staging;
    }
    
    public static DonationStaging__c generateOneTimeStaging(String customerId, String siteOrderId, String transactionId) {
        DonationStaging__c staging = generateDefaultStaging(customerId, siteOrderId, transactionId);
        staging.RecordTypeId = Utility.getRecordTypeId(Utility.STAGING_API_NAME, Utility.STAGING_RECORD_TYPE_ONE_TIME);
        return staging;
    } 
    
    public static DonationStaging__c generateInitiationStaging(String customerId, String siteOrderId, String transactionId, String card, String recurringToken) {
        DonationStaging__c staging = generateDefaultStaging(customerId, siteOrderId, transactionId);
        staging.RecordTypeId = Utility.getRecordTypeId(Utility.STAGING_API_NAME, Utility.STAGING_RECORD_TYPE_INITIATION);
        staging.Card__c = card;
        staging.RecurringToken__c = recurringToken;
        staging.OfferExpDate__c = STAGING_EXP_DATE;
        return staging;
    }
    
    public static DonationStaging__c generateRecurringStaging(String customerId, String siteOrderId, String transactionId) {
        DonationStaging__c staging = generateDefaultStaging(customerId, siteOrderId, transactionId);
        staging.RecordTypeId = Utility.getRecordTypeId(Utility.STAGING_API_NAME, Utility.STAGING_RECORD_TYPE_RECURRING);
        return staging;
    }
    public static DonationStaging__c generateFailedRecurringStaging(String customerId, String siteOrderId, String transactionId) {
        DonationStaging__c staging = generateFailedStaging(customerId, siteOrderId, transactionId);
        staging.RecordTypeId = Utility.getRecordTypeId(Utility.STAGING_API_NAME, Utility.STAGING_RECORD_TYPE_RECURRING);
        return staging;
    }
    
    public static Opportunity generateOpportunity(Id accountId, Id contactId) {
        Opportunity theOpp = new Opportunity();
        theOpp.Name = Utility.OPP_MEMBERSHIP_RECORD_TYPE;
        theOpp.StageName = 'Prospecting';
        theOpp.CloseDate = Date.today().addDays(365);
        theOpp.AccountId = accountId;
        theOpp.ContactId = contactId;
        theOpp.npsp__Primary_Contact__c = contactId;
        theOpp.RecordTypeId = Utility.getRecordTypeId('Opportunity', Utility.OPP_MEMBERSHIP_RECORD_TYPE);
        return theOpp;
    }
    
    public static Card__c generateCard(Id contId, Date validThru){
        Card__c card = new Card__c();
        card.ValidThru__c = validThru;
        card.Contact__c = contId;
        return card;
    }

    public static Campaign generateCampaign(String name, Boolean isActive) {
        Campaign campaign = new Campaign (
                Name = name,
                IsActive = isActive
        );
        return campaign;
    }

    public static GW_Volunteers__Volunteer_Job__c generateVolunteerJob(String name, String campaignId, String skills, String description, Map<String, String> loc, Boolean webDisplay) {
        GW_Volunteers__Volunteer_Job__c volunteerJob = new GW_Volunteers__Volunteer_Job__c (
                Name = name,
                GW_Volunteers__Campaign__c = campaignId,
                GW_Volunteers__Display_on_Website__c = webDisplay,
                GW_Volunteers__Skills_Needed__c = skills,
                Job_Start__c = System.now(),
                Job_End__c = System.now().addHours(1),
                Organization__c = loc.get('org'),
                Region__c = loc.get('region'),
                City__c = loc.get('city'),
                District__c = loc.get('district'),
                City_District__c = loc.get('cityDistrict'),
                Street__c = loc.get('street'),
                GW_Volunteers__Description__c = description
        );
        return volunteerJob;
    }

    public static GW_Volunteers__Volunteer_Hours__c generateVolunteerHours(String currContact, String status, String jobId) {
        GW_Volunteers__Volunteer_Hours__c volunteerHours = new GW_Volunteers__Volunteer_Hours__c (
                GW_Volunteers__Volunteer_Job__c = jobId,
                GW_Volunteers__Contact__c = currContact,
                GW_Volunteers__Status__c = status,
                GW_Volunteers__Number_of_Volunteers__c = 1,
                GW_Volunteers__Start_Date__c = Date.today()
        );
        return volunteerHours;
    }
    
    private static DonationStaging__c generateDefaultStaging(String customerId, String siteOrderId, String transactionId) {
        DonationStaging__c staging = new DonationStaging__c();
        staging.CustomerId__c = customerId;
        staging.SiteOrderId__c = siteOrderId;
        staging.TransactionId__c = transactionId;
        staging.Status__c = 'New';
        staging.BatchTimestamp__c = STAGING_BATCHTIMESTAMP;
        staging.Amount__c = STAGING_AMOUNT;
        staging.PaymentType__c = STAGING_PAYMENT_TYPE;
        return staging;
    }     

    private static DonationStaging__c generateFailedStaging(String customerId, String siteOrderId, String transactionId) {
        DonationStaging__c staging = new DonationStaging__c();
        staging.CustomerId__c = customerId;
        staging.SiteOrderId__c = siteOrderId;
        staging.TransactionId__c = transactionId;
        staging.Status__c = 'New';
        staging.BatchTimestamp__c = STAGING_BATCHTIMESTAMP;
        staging.Amount__c = STAGING_AMOUNT;
        staging.PaymentType__c = '3';
        return staging;
    }

}