force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <displayFormat>CN-{00000000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/CardNumber__c.field-meta.xml
<CustomField>
    <fullName>CardNumber__c</fullName>
    <label>Card Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Staging__c.field-meta.xml
<CustomField>
    <fullName>Staging__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staging</label>
    <referenceTo>DonationStaging__c</referenceTo>
    <relationshipLabel>Cards</relationshipLabel>
    <relationshipName>Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Card__c/fields/ValidThru__c.field-meta.xml
<CustomField>
    <fullName>ValidThru__c</fullName>
    <label>Valid Thru</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/DonationStaging__c.object-meta.xml
<CustomObject>
    <label>Donation Staging</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Donation Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donation Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DonationStaging__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Transaction amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>Card</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/OfferExpDate__c.field-meta.xml
<CustomField>
    <fullName>OfferExpDate__c</fullName>
    <label>OfferExpDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</description>
    <inlineHelpText>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/RecurringToken__c.field-meta.xml
<CustomField>
    <fullName>RecurringToken__c</fullName>
    <label>RecurringToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/SiteOrderId__c.field-meta.xml
<CustomField>
    <fullName>SiteOrderId__c</fullName>
    <description>Order number (name) assigned by the store</description>
    <label>SiteOrderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/recordTypes/Recurring.recordType-meta.xml
<RecordType>
    <fullName>Recurring</fullName>
    <active>true</active>
    <label>Recurring</label>
</RecordType>

force-app/main/default/objects/RecurringDonation__c/RecurringDonation__c.object-meta.xml
<CustomObject>
    <label>Recurring Donation</label>
    <nameField>
        <displayFormat>RD-{00000000}</displayFormat>
        <label>Recurring Donations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RecurringDonation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>RecurringDonations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/LastPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>LastPaymentDate__c</fullName>
    <description>Last success payment date</description>
    <inlineHelpText>Last success payment date</inlineHelpText>
    <label>Last Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/NextPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>NextPaymentDate__c</fullName>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/OfferExpDate__c.field-meta.xml
<CustomField>
    <fullName>OfferExpDate__c</fullName>
    <label>Offer Exp Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <formula>Contact__r.OrderNumber__c</formula>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/PaymentDay__c.field-meta.xml
<CustomField>
    <fullName>PaymentDay__c</fullName>
    <formula>Contact__r.PaymentDay__c</formula>
    <label>Payment Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/RecurringToken__c.field-meta.xml
<CustomField>
    <fullName>RecurringToken__c</fullName>
    <label>Recurring Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/Staging__c.field-meta.xml
<CustomField>
    <fullName>Staging__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staging</label>
    <referenceTo>DonationStaging__c</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>RecurringDonations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InitiatingDonationService.cls
public with sharing class InitiatingDonationService {   
    
    public static void processInitiatingDonation(List<DonationStaging__c> stagings){
        List<Lead> leads = LeadService.matchStagingWithLead(stagings);
        Map<Id, Contact> contacts = ContactService.matchStagingWithContact(stagings);
        if(!contacts.isEmpty()){
            proceedStagingForContacts(contacts, stagings);
        }
        if (!leads.isEmpty()){
            proceedStagingForLeads(leads, stagings);
        }
    }
    
    private static void proceedStagingForContacts(Map<Id, Contact> contacts, List<DonationStaging__c> stagings){
        Id contactSupporterRT = Utility.getRecordTypeId('Contact', Utility.CONTACT_SUPPORTER_RECORD_TYPE);
        Id oppMembershipRT = Utility.getRecordTypeId('Opportunity', Utility.OPP_MEMBERSHIP_RECORD_TYPE);
        List<npe01__OppPayment__c> payments = new List<npe01__OppPayment__c>();
        List<RecurringDonation__c> recurrings = new List<RecurringDonation__c>();
        List<Card__c> cards = new List<Card__c>();
        OpportunityService.replaceOpportunities(new List<Id>(contacts.keyset()));
        List<Opportunity> exsistOpps = OpportunityService.getActiveOppByContIdsAndRT(new List<Id>(contacts.keyset()), new List<Id> {oppMembershipRT});
        
        if(exsistOpps.size() < contacts.keySet().size()){
            List<Opportunity> newOpps = OpportunityService.generateMissingOpps(contacts, exsistOpps, Utility.OPP_MEMBERSHIP_RECORD_TYPE);
            insert newOpps;
            exsistOpps = OpportunityService.getActiveOppByContIdsAndRT(new List<Id>(contacts.keyset()), new List<Id> {oppMembershipRT});
        }
        deactivateRecurrings(new List<Id>(contacts.keyset()));
        deactivateCards(new List<Id>(contacts.keyset()));
        
        for(Contact theContact : contacts.values()){
            theContact.RecordTypeId = contactSupporterRT;
            for(DonationStaging__c theStaging : stagings){
                if (theContact.OrderNumber__c == theStaging.SiteOrderId__c){
                    for(Opportunity opp : exsistOpps){
                        if(opp.npsp__Primary_Contact__c == theContact.Id){
                            payments.add(DonationService.generatePayment(theStaging, opp.Id, theContact.Id));
                            recurrings.add(generateRecurring(theStaging, theContact.Id, theContact.PaymentDay__c));
                            cards.add(generateCard(theStaging, theContact.Id));
                            theStaging.Status__c = Utility.mainSettings.Default_Processed_Staging_Status__c;
                            continue;
                        }
                    }
                }
            }
        }
        insert cards;
        insert recurrings;
        for(Integer i=0; i<cards.size(); i++){
            payments[i].Card__c = cards[i].Id;
        }
        insert payments;
        update stagings;
        update contacts.values();
    } 
    
    private static void proceedStagingForLeads(List<Lead> leads, List<DonationStaging__c> stagings){
        List<npe01__OppPayment__c> payments = new List<npe01__OppPayment__c>();
        List<RecurringDonation__c> recurrings = new List<RecurringDonation__c>();
        List<Card__c> cards = new List<Card__c>();
        List<Lead> convertedLeads = LeadService.convertLeads(leads, Utility.CONTACT_SUPPORTER_RECORD_TYPE, 
                                                             Utility.OPP_MEMBERSHIP_RECORD_TYPE, Utility.OPP_MEMBERSHIP_RECORD_TYPE);
        for(Lead theLead : convertedLeads){
            for(DonationStaging__c theStaging : stagings){
                if (theLead.OrderNumber__c == theStaging.SiteOrderId__c){
                    payments.add(DonationService.generatePayment(theStaging, theLead.ConvertedOpportunityId, theLead.ConvertedContactId));
                    cards.add(generateCard(theStaging, theLead.ConvertedContactId));
                    recurrings.add(generateRecurring(theStaging, theLead.ConvertedContactId, theLead.PaymentDay__c));
                    theStaging.Status__c = Utility.mainSettings.Default_Processed_Staging_Status__c;
                    continue;
                }
            }
        } 
        insert cards;
        insert recurrings;
        for(Integer i=0; i<cards.size(); i++){
            payments[i].Card__c = cards[i].Id;
        }
        insert payments;
        update stagings;
    }
    
    private static RecurringDonation__c generateRecurring(DonationStaging__c staging, Id contId, Decimal paymentDay){
        System.debug('generate recurring for staging: ' + staging);
        RecurringDonation__c recurring = new RecurringDonation__c();
        recurring.Amount__c = staging.Amount__c;
        recurring.Staging__c = staging.Id;
        recurring.Contact__c = contId;
        recurring.RecurringToken__c = staging.RecurringToken__c;
        recurring.OfferExpDate__c = staging.OfferExpDate__c != null ? Date.valueOf(staging.OfferExpDate__c) : Date.today().addYears(1); 
       /* recurring.LastPaymentDate__c = DonationService.getLastPaymentDate(staging);
        if(Utility.SUCCESS_PAYMENT_TYPES.contains(staging.PaymentType__c)){
           recurring.NextPaymentDate__c = DonationService.getNextPaymentDate(staging.PaymentType__c, paymentDay);
        }*/
        System.debug('generate recurring: recurring' + recurring);
        return recurring;
    }
    
    public static Card__c generateCard(DonationStaging__c staging, Id contId){
        Card__c card = new Card__c();
        card.CardNumber__c = staging.Card__c;
        card.Staging__c = staging.Id;
        card.ValidThru__c = String.isBlank(staging.OfferExpDate__c) ? null : Date.valueOf(staging.OfferExpDate__c);
        card.Contact__c = contId;
        return card;
    }
    
    private static void deactivateRecurrings(List<Id> contIds){
        List<RecurringDonation__c> recurrings = getRecurringsByContIdAndStatus(contIds, 'Open');
        for (RecurringDonation__c recurring : recurrings){
            recurring.Status__c = 'Closed';
        }
        update recurrings;
    }
    
    private static void deactivateCards(List<Id> contIds){
        List<Card__c> cards = getCardsByContIdAndStatus(contIds, 'Active');
        for (Card__c theCard : cards){
            theCard.Status__c = 'Not Active';
        }
        update cards;
    }
    
    private static List<RecurringDonation__c> getRecurringsByContIdAndStatus(List<Id> contIds, String status){
        return [SELECT Id, Status__c FROM RecurringDonation__c WHERE Contact__c IN: contIds AND Status__c =: status];
    }
    
    private static List<Card__c> getCardsByContIdAndStatus(List<Id> contIds, String status){
        return [SELECT Id, Status__c FROM Card__c WHERE Contact__c IN: contIds AND Status__c =: status];
    }
    
}