force-app/main/default/objects/DonationStaging__c/DonationStaging__c.object-meta.xml
<CustomObject>
    <label>Donation Staging</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Donation Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donation Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DonationStaging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>Transaction number</description>
    <externalId>true</externalId>
    <label>TransactionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/recordTypes/Recurring.recordType-meta.xml
<RecordType>
    <fullName>Recurring</fullName>
    <active>true</active>
    <label>Recurring</label>
</RecordType>

force-app/main/default/classes/StagingService.cls
public with sharing class StagingService {
    
    private static final String ERROR_MESSAGE = 'Donation Staging must have a record type';
    
    public static Database.QueryLocator getNewStagings() {
        String stagingStatusNew = Utility.mainSettings.Default_New_Staging_Status__c;
        List<String> stagingFields = Utility.getObjectFields(Utility.STAGING_API_NAME);
        String query = 'SELECT RecordType.Name, ' + String.join((Iterable<String>)stagingFields, ',');
        query += ' FROM DonationStaging__c WHERE Status__c =: stagingStatusNew LIMIT 50000';
        return Database.getQueryLocator(query);
    }
    
    public static void proceedInsertings(List<DonationStaging__c> stagings) {
        System.debug('StagingService.proceedInsertings()');
        System.debug('List<DonationStaging__c> stagings = ' + stagings);
        Set<String> transactionIds = new Set<String>();
        for (DonationStaging__c staging: stagings){
            transactionIds.add(staging.TransactionId__c);
        }
        System.debug('Stagings to be inserted - ' + stagings);
        insert stagings;
    }
    
    public static void proceedStagingConversion(List<DonationStaging__c> stagings){
        Donation separated = separateStagings(stagings);
        if(!separated.oneTime.isEmpty()){
            OneTimeDonationService.processOneTimeDonation(separated.oneTime);
        }
        if(!separated.initiating.isEmpty()){
            InitiatingDonationService.processInitiatingDonation(separated.initiating);
        }
        if(!separated.recurring.isEmpty()){
            RecurringDonationService.processRecuringDonation(separated.recurring);
        }
    }
    
    private static Donation separateStagings(List<DonationStaging__c> stagings){
        Donation wrapper = new Donation();
        List<DonationStaging__c> oneTime = new List<DonationStaging__c>();
        List<DonationStaging__c> initiating  = new List<DonationStaging__c>();
        List<DonationStaging__c> recurring  = new List<DonationStaging__c>();
        for (DonationStaging__c st : stagings){
            if(st.RecordType.Name == Utility.STAGING_RECORD_TYPE_RECURRING){
                recurring.add(st);
            } else if(st.RecordType.Name == Utility.STAGING_RECORD_TYPE_INITIATION){
                initiating.add(st);
            }else if (st.RecordType.Name == Utility.STAGING_RECORD_TYPE_ONE_TIME){
                oneTime.add(st);
            }
        }
        wrapper.oneTime = oneTime;
        wrapper.initiating = initiating;
        wrapper.recurring = recurring;
        return wrapper;
    } 
    
}