force-app/main/default/objects/DonationStaging__c/DonationStaging__c.object-meta.xml
<CustomObject>
    <label>Donation Staging</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Donation Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donation Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DonationStaging__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</description>
    <inlineHelpText>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RestRecurringPaymentGenerator.cls
@RestResource(urlMapping='/recurringpayment/*')
global class RestRecurringPaymentGenerator {

    @HttpPOST
    global static void doPost() {
        
        System.debug('RestRecurringPaymentGenerator.doPost()');
        try{
            List<Integration_Log__c> logs = new List<Integration_Log__c>();

            String xmlString = RestContext.request.requestBody.toString();
            
            logs.add(
                Utility.configureIntegrationLog(
                    'WebPay', 
                    Utility.LogLevels.DEBUG,
                    Utility.STAGING_RECORD_TYPE_RECURRING,
                    'RestRecurringPaymentGenerator: Request Body',
                    xmlString
                )
            );

            DonationStaging__c newStaging = ParseService.parseXML(xmlString);
            System.debug('DonationStaging__c newStaging = ' + newStaging);
            newStaging.RecordTypeId = Utility.getRecordTypeId(Utility.STAGING_API_NAME, Utility.STAGING_RECORD_TYPE_RECURRING);
            
            
            //newStaging.PaymentType__c = '8';//FOR TESTING! REMOVE BEFORE DEPLOYING!
            
            
            StagingService.proceedInsertings(new List<DonationStaging__c> {newStaging});

            logs.add(
                Utility.configureIntegrationLog(
                    'WebPay', 
                    Utility.LogLevels.DEBUG,
                    Utility.STAGING_RECORD_TYPE_RECURRING,
                    'RestRecurringPaymentGenerator: Created DonationStaging__c', 
                    JSON.serialize(newStaging)
                )
            );
            
            insert logs;

            System.debug('RestClient.getXMLResponse() = ' + RestClient.getXMLResponse());

            RestClient.response(200, RestClient.getXMLResponse());
            
        }catch(Exception e){
            Integration_Log__c log = Utility.configureIntegrationLog(
                'WebPay', Utility.LogLevels.ERROR,
                Utility.STAGING_RECORD_TYPE_RECURRING,
                'RestRecurringPaymentGenerator: Exception ' + e.getTypeName(),
                e.getMessage()
            );
            insert log;

            System.debug('RestRecurringPaymentGenerator Exception: '+ LoggingLevel.ERROR + e.getTypeName() + ' ' + e.getMessage());
            RestClient.response(400, e.getTypeName() + ' ' + e.getMessage());
        }
    }
    
}