force-app/main/default/objects/DonationStaging__c/DonationStaging__c.object-meta.xml
<CustomObject>
    <label>Donation Staging</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Donation Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donation Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RecurringDonation__c/RecurringDonation__c.object-meta.xml
<CustomObject>
    <label>Recurring Donation</label>
    <nameField>
        <displayFormat>RD-{00000000}</displayFormat>
        <label>Recurring Donations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RecurringDonation__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <formula>Contact__r.CustomerId__c</formula>
    <label>CustomerId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <formula>Contact__r.OrderNumber__c</formula>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentTriggerTest.cls
@isTest
private class PaymentTriggerTest {
    
    @testSetup
    private static void setup() {
        TestDataFactory.createTestData();
        Contact john = [SELECT CustomerId__c, OrderNumber__c FROM Contact WHERE Name = 'John Smith'];

        DonationStaging__c donationStaging = TestDataFactory.generateFailedRecurringStaging(john.CustomerId__c, john.OrderNumber__c, '123456781');
        insert donationStaging;

        RecurringDonation__c rd = TestDataFactory.generateRecurringDonation(10, john.Id, System.today(), System.today().addDays(1));
        insert rd;
        
        Account acc = [SELECT Id FROM Account WHERE Name = 'Red Cross' LIMIT 1];
        Opportunity opp = TestDataFactory.generateOpportunity(acc.Id, john.Id);
        insert opp;
    }
    
    @isTest
    private static void getDependentPicklistValuesTest() {
        Test.startTest();
        Boolean run = PaymentHandler.runOnce('onAfterInsert');
        Boolean run2 = PaymentHandler.runOnce('onAfterInsert');
        Boolean run3 = PaymentHandler.runOnce('onAfterInsert');
        Test.stopTest();
        System.assertEquals(run, TRUE, '');
        System.assertEquals(run2, FALSE, '');
        System.assertEquals(run3, FALSE, '');
    }
    
}