force-app/main/default/objects/DonationStaging__c/DonationStaging__c.object-meta.xml
<CustomObject>
    <label>Donation Staging</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Donation Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donation Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DonationStaging__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Transaction amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/BatchTimestamp__c.field-meta.xml
<CustomField>
    <fullName>BatchTimestamp__c</fullName>
    <description>Time of transaction execution</description>
    <externalId>true</externalId>
    <label>BatchTimestamp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</description>
    <inlineHelpText>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/RecurringToken__c.field-meta.xml
<CustomField>
    <fullName>RecurringToken__c</fullName>
    <label>RecurringToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/SiteOrderId__c.field-meta.xml
<CustomField>
    <fullName>SiteOrderId__c</fullName>
    <description>Order number (name) assigned by the store</description>
    <label>SiteOrderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/recordTypes/Recurring.recordType-meta.xml
<RecordType>
    <fullName>Recurring</fullName>
    <active>true</active>
    <label>Recurring</label>
</RecordType>

force-app/main/default/objects/RecurringDonation__c/RecurringDonation__c.object-meta.xml
<CustomObject>
    <label>Recurring Donation</label>
    <nameField>
        <displayFormat>RD-{00000000}</displayFormat>
        <label>Recurring Donations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Donations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RecurringDonation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>RecurringDonations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <formula>Contact__r.CustomerId__c</formula>
    <label>CustomerId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/LastPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>LastPaymentDate__c</fullName>
    <description>Last success payment date</description>
    <inlineHelpText>Last success payment date</inlineHelpText>
    <label>Last Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/NextPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>NextPaymentDate__c</fullName>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <formula>Contact__r.OrderNumber__c</formula>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/PaymentDay__c.field-meta.xml
<CustomField>
    <fullName>PaymentDay__c</fullName>
    <formula>Contact__r.PaymentDay__c</formula>
    <label>Payment Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/RecurringToken__c.field-meta.xml
<CustomField>
    <fullName>RecurringToken__c</fullName>
    <label>Recurring Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/Staging__c.field-meta.xml
<CustomField>
    <fullName>Staging__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staging</label>
    <referenceTo>DonationStaging__c</referenceTo>
    <relationshipLabel>Recurring Donations</relationshipLabel>
    <relationshipName>RecurringDonations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecurringDonation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RecurringDonationService.cls
public with sharing class RecurringDonationService {
        
    public static Database.QueryLocator getTodaysActiveRecurrings() {
        Date today = System.today();
        String recurringDonationStatusOpen = 'Active'; //Utility.mainSettings.Recurring_Active_Donation_Status__c;
        String query = 'SELECT Amount__c, CustomerId__c, OrderNumber__c, Email__c, RecurringToken__c ';
        query += ' FROM RecurringDonation__c WHERE Status__c =: recurringDonationStatusOpen AND NextPaymentDate__c =: today LIMIT 50000';
        return Database.getQueryLocator(query);
    }
    
    public static void processRecuringDonation(List<DonationStaging__c> stagings){
        System.debug('RecurringDonationService.processRecuringDonation(), stagings = ' + stagings);
        Map<Id, Contact> contacts = ContactService.matchStagingWithContact(stagings);
        System.debug('RecurringDonationService.processRecuringDonation(), contacts = ' + contacts);
        if(!contacts.isEmpty()){
            proceedStagingForContacts(contacts, stagings);
        }
    }
    
    public static List<RecurringDonation__c> getOpenRecurringsByContactIds(List<Id> contactIds) {
        return [SELECT Id, NextPaymentDate__c, Contact__c, PaymentDay__c, LastPaymentDate__c, Staging__c, Staging__r.PaymentType__c, Staging__r.BatchTimestamp__c
                FROM RecurringDonation__c 
                WHERE Contact__c IN: contactIds 
                AND Status__c =: Utility.mainSettings.Recurring_Active_Donation_Status__c
                LIMIT 50000];
    }
    
    private static void proceedStagingForContacts(Map<Id, Contact> contacts, List<DonationStaging__c> stagings){
        Id membershipRT = Utility.getRecordTypeId('Opportunity', Utility.OPP_MEMBERSHIP_RECORD_TYPE);
        List<npe01__OppPayment__c> payments = new List<npe01__OppPayment__c>();
       // List<RecurringDonation__c> recurrings = new List<RecurringDonation__c>();
        List<Opportunity> exsistOpps = OpportunityService.getActiveOppByContIdsAndRT(new List<Id> (contacts.keyset()), new List<Id> {membershipRT});
        if(exsistOpps.size() != contacts.keySet().size()){
            List<Opportunity> newOpps = OpportunityService.generateMissingOpps(contacts, exsistOpps, Utility.OPP_MEMBERSHIP_RECORD_TYPE);
            insert newOpps;
            exsistOpps = OpportunityService.getActiveOppByContIdsAndRT(new List<Id> (contacts.keyset()), new List<Id> {membershipRT});
        }        
        for(Contact theContact : contacts.values()){
            System.debug('theContact = ' + theContact);
            for(DonationStaging__c theStaging : stagings){
                if (theContact.OrderNumber__c == theStaging.SiteOrderId__c) {
                    for(Opportunity opp : exsistOpps){
                        if(opp.npsp__Primary_Contact__c == theContact.Id){
                            payments.add(DonationService.generatePayment(theStaging, opp.Id, theContact.Id));
                            theStaging.Status__c = Utility.mainSettings.Default_Processed_Staging_Status__c;
                            System.debug('theStaging.Status__c = ' + theStaging.Status__c);
                            // RecurringDonation__c oldRecurring = theContact.RecurringDonations__r[0];
                          //  updateRecurring(oldRecurring, theStaging);
                         //   recurrings.add(oldRecurring);
                            continue;
                        }
                    }
                }
            }
        }
        System.debug('payments = ' + payments);
        System.debug('stagings = ' + stagings);
        insert payments;
        update stagings;
      //  update recurrings;
    }
    
  /*  private static void updateRecurring(RecurringDonation__c recurring, DonationStaging__c theStaging){
        system.debug('updateRecurring: ' + recurring);
            recurring.NextPaymentDate__c = DonationService.getNextPaymentDate(theStaging.PaymentType__c, recurring.PaymentDay__c);
        Date lastPaymentDate = DonationService.getLastPaymentDate(theStaging);
        if(lastPaymentDate != null){
            recurring.LastPaymentDate__c = lastPaymentDate;
        }
    }*/
    
}