force-app/main/default/objects/DonationStaging__c/DonationStaging__c.object-meta.xml
<CustomObject>
    <label>Donation Staging</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Donation Staging Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donation Stagings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DonationStaging__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Transaction amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/PaymentType__c.field-meta.xml
<CustomField>
    <fullName>PaymentType__c</fullName>
    <description>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</description>
    <inlineHelpText>Successfully payment 1, 4, 10 
Canceled payment 5, 7, 9 
======================= 
1 - Completed 
2 - Declined 
3 - Pending 
4 - Authorized 
5 - Refunded 
6 - System 
7 - Voided 
8 - Failed 
9 - Partial Voided 
10 - Recurrent</inlineHelpText>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DonationStaging__c/fields/SiteOrderId__c.field-meta.xml
<CustomField>
    <fullName>SiteOrderId__c</fullName>
    <description>Order number (name) assigned by the store</description>
    <label>SiteOrderId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LandingAmountWebservice.cls
@RestResource(urlMapping='/landingamount/*')
global class LandingAmountWebservice {
    static final Date FROM_DATE = Date.newinstance(2020, 12, 18);

    @HttpGet
    global static void doGet() {
        String siteorder = RestContext.request.params.get('siteorder');
        if (String.isNotBlank(siteorder)) {
            Object webserviceResponse = getTotalPayments(siteorder);
            if (webserviceResponse != null) sendResponse(webserviceResponse);
            else sendResponse(0);
        } else sendResponse('Incorrect resource query param!');
    }

    /*static Object getTotalPayments(String requestBody) {
        String siteOrder = '%' + requestBody + '%';
        List<AggregateResult> paidOppPayments = [
            SELECT SUM(npe01__Payment_Amount__c)
            FROM npe01__OppPayment__c
            WHERE npe01__Paid__c = true
                AND Staging__c IN (
                        SELECT Id
                        FROM DonationStaging__c
                        WHERE SiteOrderId__c LIKE :siteOrder
                            AND CreatedDate >= :FROM_DATE
                    )
        ];*/

//hotfix by Eugene K.
        static Object getTotalPayments(String requestBody) {
            String siteOrder = '%' + requestBody + '%';
            List<AggregateResult> paidOppPayments = [
                    SELECT SUM(Amount__c)
                    FROM DonationStaging__c
                    WHERE (PaymentType__c = '1' OR PaymentType__c = '4')
                    AND SiteOrderId__c LIKE :siteOrder
                    AND CreatedDate >= :FROM_DATE
            ];


            return paidOppPayments[0].get('expr0');
    }

    static void sendResponse(Object serviceResponse) {
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody = Blob.valueOf(String.valueOf(serviceResponse));
    }
}